### ISSUE TITLE
App doesn't work with node version 22.6.0

### ISSUE THREAD

**Issue by Kungfoosian** [yournextstore/yournextstore#11]
In dev mode, I ran into issues loading products from Stripe when my Node version is 22.6.0. I noticed the warning ` WARN  Unsupported engine: wanted: {"node":"^20.11.1"} (current: {"node":"v22.6.0","pnpm":"9.6.0"})` when `pnpm dev` was run, switch to Node version 20.11.1 using `nvm`, and the issue was resolved.

**Steps to reproduce Error**

- Follow the steps detailed in **README**, stop at section "Variants"
- Make sure Node is at least version **22.6.0**
- Run `pnpm dev`
- Visit the URL defined in `.env`  file, variable **NEXT_PUBLIC_URL**. In my case: `http://localhost:3000`
- **Output**
[error-node-22-6-0.txt](https://github.com/user-attachments/files/16567563/error-node-22-6-0.txt)

**Fix**
- Switch Node to version **20.11.1**, using `nvm`
- **Output**
[normal-node-20-11-1.txt](https://github.com/user-attachments/files/16567562/normal-node-20-11-1.txt)

**Comment by Kungfoosian** [comment]
Besides the warning going away, it still gave me this error  when  fetching products:

>  ⨯ node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/index.mjs (587:1) @ get error
 ⨯ ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "slug"
    ],
    "message": "Required"
  }
]
    at Array.map (<anonymous>)
    at async Home (./src/app/(store)/page.tsx:37:22)
digest: "1932983191"
  585 |                 if (this._error)
  586 |                     return this._error;
\> 587 |                 const error = new ZodError(ctx.common.issues);
      | ^
  588 |                 this._error = error;
  589 |                 return this._error;
  590 |             },
 GET / 500 in 27084ms
 │ GET https://api.stripe.com/v1/products?limit=100&active=true&expand[0]=data.default_price 200 in 195ms (cache hit)
 │ GET https://api.stripe.com/v1/account?expand[0]=settings.branding.logo 200 in 588ms (cache skip)
 │ │ Cache skipped reason: (auto no cache)

**Comment by typeofweb** [comment]
There's an error from Zod when validating product metadata:
```json
{
  "code": "invalid_type",
  "expected": "string",
  "received": "undefined",
  "path": ["slug"],
  "message": "Required"
}
```
It means that one of the products doesn't have the `metadata.slug` field defined.

**Comment by Kungfoosian** [comment]
i only have one product with `metadata.slug` defined, here is the output when i run the app with node version 20.11.1. No issues loading products

>xxx@yyyy:\~/code/yournextstore$ node --version
v20.11.1
xxx@yyyy:\~/code/yournextstore$ pnpm dev
\> yournextstore@1.12.0 dev /home/xxx/code/yournextstore
\> next dev
  ▲ Next.js 15.0.0-canary.102
  >- Local:        http://localhost:3000
  >- Environments: .env
  >- Experiments (use with caution):
    · ppr
    · after
    · turbo
    · ...
 ✓ Starting...
   automatically enabled Fast Refresh for 1 custom loader
 ✓ Ready in 2.6s
 ○ Compiling / ...
 ✓ Compiled / in 5.4s (1070 modules)
 GET / 200 in 6984ms
 │ GET https://api.stripe.com/v1/products?limit=100&active=true&expand[0]=data.default_price 200 in 78ms (cache hit)
 │ GET https://api.stripe.com/v1/account?expand[0]=settings.branding.logo 200 in 729ms (cache skip)
 │ │ Cache skipped reason: (auto no cache)
 │ GET https://api.stripe.com/v1/payment_intents/pi_3Pm1MERsSuW4Npiw1GYd5i3Y?expand[0]=payment_method 200 in 130ms (cache hit)
 │ GET https://api.stripe.com/v1/products/prod_QdH9MsBGZE7LZr?expand[0]=default_price 200 in 4ms (cache hit)
 ○ Compiling /products ...
 ✓ Compiled /products in 1170ms (1075 modules)
 GET /products 200 in 1449ms
 │ GET https://api.stripe.com/v1/products?limit=100&active=true&expand[0]=data.default_price 200 in 2ms (cache hit)
