### ISSUE TITLE
Inquiries regarding use

### ISSUE THREAD

**Issue by alt-vena** [yournextstore/yournextstore#12]
Hello, I am trying to develop an Ecommerce sites with various payment options such as credit cards, PayPal, and Stripe. Would it be okay to use this repository as the basis?

**Comment by typeofweb** [comment]
Stripe supports PayPal and credit cards, let me know if they don’t work for you in Your Next Store.

Feel free to use the repository in accordance with the AGPL license.

**Comment by alt-vena** [comment]
Thank you for your support.
