### ISSUE TITLE
Add Support for Multiple Images in Product

### ISSUE THREAD

**Issue by mattyx97** [yournextstore/yournextstore#18]
I would like to request the addition of a feature that allows users to upload multiple images for product listings, even though I understand that Stripe currently only supports a single image per product.

Motivation:
Allowing multiple images would significantly enhance the user experience by providing a more comprehensive view of the products. This is especially important for businesses that sell items with various angles or details that need to be showcased. While Stripe currently restricts uploads to a single image, having the option to manage multiple images within the platform would be a valuable feature for many users.

**Comment by typeofweb** [comment]
It's true that Stripe only allows for uploading a single product image. Surprisingly, though, Stripe supports multiple images per product via the API!

We're working on this, but we can't promise any timeline yet.

**Comment by mattyx97** [comment]
I wasn't aware of that, and it's fantastic!
Thanks

**Comment by zaiste** [comment]
@mattyx97 it's implemented cc 857fd70
