### ISSUE TITLE
Add Support for Product Quantities in Listings

### ISSUE THREAD

**Issue by mattyx97** [yournextstore/yournextstore#19]
I would like to request the addition of support for managing product quantities in listings, as this is a fundamental feature for any eCommerce platform.

Motivation:

Managing product quantities is crucial for any online store, as it allows sellers to track inventory, prevent overselling, and manage stock levels effectively. Without the ability to specify and update quantities, it becomes challenging to operate a fully functional eCommerce business. This feature is essential for ensuring that customers can only purchase items that are in stock and helps streamline the order management process.

Proposed Solution:

Implement a quantity field for each product listing maybe as meta_tag in stripe, allowing sellers to specify the available stock.
Allow automatic updates to quantities when purchases are made, reducing the inventory count accordingly.
Provide warnings or restrictions if a customer attempts to purchase more than the available stock or if there are low stock.

**Comment by typeofweb** [comment]
Did you generate this issue with GPT?

**Comment by mattyx97** [comment]
No,Why?
I just added a lot of details to make you understand better and maybe simplify your work

**Comment by mattyx97** [comment]
To tackle the issue more simply (at least initially) , you could use a less “real-time” stock management approach. Basically, you don’t need to handle every update instantaneously. You could set up the stock quantities and make products show as unavailable once they drop below a certain level. This way, you avoid managing updates in real time and simplify stock management.

**Comment by zaiste** [comment]
@mattyx97 basic stock handling is now implemented 🎉

**Comment by mattyx97** [comment]
> @mattyx97 basic stock handling is now implemented 🎉

Which is the stripe Metadata?

**Comment by JoNilsson** [comment]
> @mattyx97 basic stock handling is now implemented 🎉

Where is this functionality documented?   There was not commit hash mentioned in your comment when you marked it completed.  That would be sufficient for me to figure out how it's supposed to work.

**Comment by FionnD** [comment]
Hi @zaiste Can you explain a little how stock handling can be used/implemented?

**Comment by kyleslie2** [comment]
Is there any documentation for this?
