### ISSUE TITLE
Problem fetching products locally

### ISSUE THREAD

**Issue by lappemic** [yournextstore/yournextstore#25]
I'm having trouble fetching products in my local development environment. The online version works fine, but locally, I can't get the products to show up.

## What I've tried
- Checked that my environment variables are set correctly
- Verified that my Stripe account has products set up

## Questions
1. How should I set up my local environment to fetch products correctly?
2. Are there any specific steps I need to take with `commerce-kit` for local development?
3. Should I be using Stripe webhooks for local product syncing? If so, how?

## Additional Information
- The online version of the store successfully fetches and displays products
- No error messages are showing up, the products just aren't appearing

Any help or guidance would be greatly appreciated!

**Comment by lappemic** [comment]
No, not getting any errors. Just seing the discover our curated collection, accessories and and apparel cards.

**Comment by RedstonePfalz** [comment]
Could it be that you have not assigned your products to one of the two categories? If so, you won't be able to see them when you click on the categories. So far, you cannot define your own categories.

**Comment by lappemic** [comment]
i did not assign any category. Nevertheless in the deployed version they appear on the main page (due to the `const products = await Commerce.productBrowse({ first: 6 });` in `src/app/(store)/page.tsx') but not locally.

**Comment by typeofweb** [comment]
Try clearing out cache (`rm -rf .next`)

**Comment by zaiste** [comment]
@lappemic probably cache related. Closing for now. Feel free to re-open if the problem persists

**Comment by lappemic** [comment]
Confirm that it was cache related. Thanks a lot for the help!
