### ISSUE TITLE
Local build fails due to 'contextGet' import error from 'commerce-kit'

### ISSUE THREAD

**Issue by lappemic** [yournextstore/yournextstore#26]
When building the project locally on an M2 MacBook Pro, i encounter an error stating that 'contextGet' is not exported from 'commerce-kit'. However, the same code builds and runs successfully on Vercel.

## Error Message
```
Attempted import error: 'contextGet' is not exported from 'commerce-kit' (imported as 'Commerce').
```

This error occurs in multiple files:
- `./src/app/(store)/page.tsx`
- `./src/ui/footer/Footer.tsx`
- `./src/ui/nav/Nav.tsx`

## Environment
- Local Machine: MacBook Pro M2
- Deployment: Vercel (working correctly)
- Branch: main (same for both local and Vercel)

## Steps to Reproduce
1. Clone the repository
2. Install dependencies
3. Run the build process locally

## Expected Behavior
The project should build and run locally without any import errors.

## Actual Behavior
The build process fails with the aforementioned import error.

## Additional Context
- The error suggests that there might be a discrepancy between the local 'commerce-kit' package and the one used in the Vercel deployment.
- It's possible that the 'contextGet' function is not properly exported in the local version of 'commerce-kit'.
- There might be differences in how the dependencies are resolved locally vs. on Vercel.

Do you have any idea why this is happening? Happy for every input!

**Comment by zaiste** [comment]
@lappemic This should work now. Could you do `pnpm up` to double check and re-open if needed
