### ISSUE TITLE
Add new image

### ISSUE THREAD

**Issue by juanfernandes** [yournextstore/yournextstore#30]
I'm not new to web development. I'm not a Js expert and I'm new to Next.js. 

I want to replace the top image on the homepage (coffee cup). I've put a new image in the src/images folder but it never gets copied to the static media folder or public folders. 

I assume I need to tell web pack to include that image but can't find where to do this. 

Should I just use a CDN image instead, as the current one is hosted on Stripe.

```
					<Image
						alt="Hoodies"
						loading="eager"
						priority={true}
						className="rounded"
						height={450}
						width={450}
						src="/images/hero.png"
						style={{
							objectFit: "cover",
						}}
						sizes="(max-width: 640px) 70vw, 450px"
					/>
```

Console error: 

```
GET http://localhost:3000/_next/image?url=/images/hero.png&w=640&q=75](http://localhost:3000/_next/image?url=%2Fimages%2Fhero.png&w=640&q=75)
```

**Comment by zaiste** [comment]
@juanfernandes you need to `import` the image file and pass it to the `<Image />` component as `src`. Check this for inspiration: https://github.com/yournextstore/yournextstore/blob/60e34baca6c49263f3c34cdaee249d21658bb17f/src/app/(store)/page.tsx#L7
