### ISSUE TITLE
Build error when deployed to Vercel

### ISSUE THREAD

**Issue by yansusanto** [yournextstore/yournextstore#32]
I'm encountering the following error when deploying to Vercel. Can anyone in the know advise me on what the issue is?

```
Failed to build /sitemap.xml/route: /sitemap.xml after 1 attempts.

Error occurred prerendering page "/sitemap.xml". Read more: https://nextjs.org/docs/messages/prerender-error
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "slug"
    ],
    "message": "Required"
  }
]
```

Thank you.

**Comment by RedstonePfalz** [comment]
I think, you don't have set the slug metadata in your Stripe product.

**Comment by yansusanto** [comment]
@RedstonePfalz how exactly do we set the slug metadata?

**Comment by RedstonePfalz** [comment]
It's described in the section "Add products" and "Metadata" of the Readme.

**Comment by zaiste** [comment]
Thanks for your help @RedstonePfalz
