### ISSUE TITLE
Is it possible to add other metadata other than those established in the documentation?

### ISSUE THREAD

**Issue by SeanLuis** [yournextstore/yournextstore#33]
I'm trying to access new metadata and it doesn't appear.
<img width="317" alt="image" src="https://github.com/user-attachments/assets/a28e226a-b3cf-47b8-8364-03e861559e9c">

`{
    "id": "prod_Ql2dds8f6FTmde",
    "object": "product",
    "active": true,
    "attributes": [],
    "created": 1725030963,
    "description": "É feita com fio de malha premium, acessórios de metal e zíper. Tem forro em tecido de algodão. Pode ser feita na cor da sua escolha segundo a disponibilidade da loja.",
    "images": [
        "https://files.stripe.com/links/MDB8YWNjdF8xUHRWaDRGTU9ESHFqNm1sfGZsX3Rlc3RfWnAwZU5naXZNNzZOQWpPZWwyYTRLTnhO00wbPsgaZj"
    ],
    "livemode": false,
    "metadata": {
        "category": "bags",
        "slug": "bag-galacia"
    },
    "name": "Galácia",
    "package_dimensions": null,
    "shippable": null,
    "statement_descriptor": "galacia",
    "tax_code": null,
    "type": "service",
    "unit_label": "GP007",
    "updated": 1725034893,
    "url": null,
    "default_price": {...},
    "marketing_features": []
}`

**Comment by zaiste** [comment]
@SeanLuis, we’re focused on great DX right now, but share your case, and we might consider adding it

**Comment by zaiste** [comment]
@SeanLuis closing, let us know about specific metadata to add
