### ISSUE TITLE
Loading state for basket item removal causes horizontal scroll

### ISSUE THREAD

**Issue by andreaselia** [yournextstore/yournextstore#36]
You can just about see the spinners cut off on the right of the total.

![CleanShot 2024-09-10 at 19 42 41@2x](https://github.com/user-attachments/assets/f260a15b-a422-47f9-a066-1fe5b0e11913)

**Comment by NacomiTagiera** [comment]
I can fix that

**Comment by zaiste** [comment]
@NacomiTagiera ping

**Comment by NacomiTagiera** [comment]
@andreaselia I personally think it looks better when the loading indicator is slightly higher than the price. Previously, it was at the same height but positioned to the right.
You're right that there seems to be an issue with the cart item removal.

**Comment by andreaselia** [comment]
Each to their own, I think it looks weird given it's vertically aligned in the center everywhere else on the site (like when adding items to the cart).
