### ISSUE TITLE
Products Missing Metadata Cause App to Break – Should be Ignored

### ISSUE THREAD

**Issue by DOSputin** [yournextstore/yournextstore#38]
Products Missing Metadata Cause App to Break

**Comment by JoNilsson** [comment]
Looking into this further,  looks like the main issue is in the yns `commerce-kit` npm package source here:

```js
// Define product metadata schema
var ut = c.object({
  category: c.string().optional(),
  order: c.coerce.number().optional(),
  slug: c.string(), // <-- this is what is breaking everything.   
  variant: c.string().optional(),
  stock: c.coerce.number().optional().transform((t) => (t === void 0 ? Infinity : t)),
});
```

You could just modify that to make the string an optional, or nullable, and it won't break.  That won't solve the problem entirely though,  If you have items in the Stripe catalog of products that you don't want to display, you'd have to do some more work to create a method for excluding them from enumeration on the front-end. 

For that we'd need something like 
```js
  // Filter products that have `exclude_from_site` metadata or missing slug
  const validProducts = products.filter((product) => {
    return !product.metadata?.exclude_from_site && product.metadata?.slug;
  });
  ```
