### ISSUE TITLE
404 Error Link in Vercel Deployment

### ISSUE THREAD

**Issue by iynewz** [yournextstore/yournextstore#45]
I encountered a 404 error when accessing the following link:

https://github.com/yournextstore/yournextstore/tree/upcoming?tab=readme-ov-file#add-environmental-variables

This is where the link is in the page:

![image](https://github.com/user-attachments/assets/b18c7299-5370-40cc-81f4-289957a28d8e)

Please check the validity of this link. Thank you! You did an amazing job!

**Comment by RedstonePfalz** [comment]
The correct link:
https://github.com/yournextstore/yournextstore?tab=readme-ov-file#add-environment-variables

**Comment by zaiste** [comment]
@iynewz Yes, as pointed by @RedstonePfalz you need to set those env variables. Let us know if it worked for you!

**Comment by elarber** [comment]
演示网站我也打不开
