### ISSUE TITLE
Cart icon in the top right corner updates after the second item was put into the cart

### ISSUE THREAD

**Issue by AuspeXeu** [yournextstore/yournextstore#5]

**Comment by r0ld3x** [comment]
assign me :)

**Comment by typeofweb** [comment]
@r0ld3x there's no need to assign; feel free to open a PR

**Comment by r0ld3x** [comment]
okay :)

**Comment by r0ld3x** [comment]
Getting 
`Internal error: Error: The search feature is temporarily unavailable in your region.`
because search features is not available in my country.

**Comment by typeofweb** [comment]
Stripe in India is currently only available on invite-only basis.
See: https://stripe.com/global

**Comment by r0ld3x** [comment]
I have Indian stripe account.

**Comment by zaiste** [comment]
@AuspeXeu we observed something similar in the past, but with the new Next.js versions it seems to be OK now. Could you confirm or re-open if you still have it?
