### ISSUE TITLE
Application crash when Products doesn't have Default price

### ISSUE THREAD

**Issue by pdanysz** [yournextstore/yournextstore#66]
Hi,

I encountered an issue when running the app and connecting to Stripe (dev env). The app crashes because it expects products with a default price.

In my Stripe test account, I have several products created on-the-fly, many without a default price.

```
Unhandled Runtime Error

[ Server ] Error: Product must have a default price

Source
src/app/(store)/page.tsx (17:19) @ async Home

  15 |
  16 | export default async function Home() {
> 17 | 	const products = await Commerce.productBrowse({ first: 6 });
     | 	                 ^
  18 | 	const t = await getTranslations("/");
  19 |
  20 | 	return (
```

I used a workaround by adding filters to fetch products from Stripe:

```javascript
const products = await Commerce.productBrowse({ first: 6, category: "general" });
```

It would be good to fix this at the base level to only pull products with a default price or handle the issue differently. :)

Regards

**Comment by zaiste** [comment]
@pdanysz it seems it's no longer possible to create a product without a default price in Stripe. We've implemented a fix to handle this situation i.e. a product without the default price cf. da192da8e7bce1aed74b18e7f1bbc581ca538d13

**Comment by miguelgargallo** [comment]
Same error, just git clone, try to deploy, and stuck here, 2025
