### ISSUE TITLE
Feature request: Instead of 'Add to Cart' it can be a link

### ISSUE THREAD

**Issue by DealsBeam** [yournextstore/yournextstore#7]
So the store can be used as an affiliate store that links to other websites, instead of buying products directly from within the site.

**Comment by r0ld3x** [comment]
tell me some detail

**Comment by typeofweb** [comment]
It can be anything you want, although it doesn't make sense. If it's simply an affiliate catalog, then you don't need Stripe or most of the things we've implemented.
