### ISSUE TITLE
Stripe adds a product, and it's a one-time payments. It doesn't seem to work either.

### ISSUE THREAD

**Issue by monsterooo** [yournextstore/yournextstore#9]
⨯ node_modules/.pnpm/commerce-kit@0.0.11_@types+node@20.14.14_next@15.0.0-canary.102_@babel+core@7.24.9_babel-plug_2o7dptzv6yc5lwdbxnzwjv3uva/node_modules/commerce-kit/dist/index.js (1:93) @ _
 ⨯ Error: Product must have a default price
    at Array.map (<anonymous>)
    at async Home (./src/app/(store)/page.tsx:35:22)
digest: "4056400387"

**Comment by typeofweb** [comment]
That would happen if the product didn’t have the default price defined. Can you screenshot how the product is configured, if that’s not private?

**Comment by zaiste** [comment]
@monsterooo let us know if you still have problems setting it up and re-open if needed
